<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="test"
    errors="0" failures="1" hostname="" id="" package="test" skipped="0"
    tests="1" time="13.91" timestamp="Thu, 18 Jan 2018 13:32:41 GMT">
  
    <testcase name="default e2e tests" classname="test" time="13.91" assertions="2">

      <failure message="Testing if element &lt;.hello&gt; is present.">    at Object.defaultE2eTests [as default e2e tests] (/home/kbonduel/projects/kevin.bonduelle/ovh-icon-database-front/test/e2e/specs/test.js:14:15)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
